### PR TITLE
feature: check editors to install

### PR DESCRIPTION
**Pull request by jvelezpo**
This branch leaves from  https://github.com/wakatime/desktop/pull/50

* loads only installed editors
* opacity 0.6 to editors that dont have wakatime plugin installed
* loader icon when installing the plugins
* refresh the view after installing the plugin
* uses `useStyles` hook for styles, makes the components more readable
* add static method to get name of editor so there is no need to instantiate it (save RAM)

### CODE REVIEW

**Comment by gandarez** [comment]
Is possible to add an individual install button for each editor in this sprint?

**Comment by jvelezpo** [comment]
> Is possible to add an individual install button for each editor in this sprint?

yes working on it right now

**Comment by gandarez** [comment]
I think instead of duplicating `name` property we should use `key` property from base class `Editor`. The problem is that property isn't static.

**Comment by jvelezpo** [comment]
> I think instead of duplicating `name` property we should use `key` property from base class `Editor`. The problem is that property isn't static.

I created static methods `getName` inside each editor class
but we can always make `name` or `key` static, waht do you think @gandarez ?

**Comment by gandarez** [comment]
Making it static won't break anything?

**Comment by gandarez** [comment]
Thanks.

**Pull request merged**
